.TH IDLE 1 "30 Apr 1991"
.UC
.SH NAME 
idler \- Displays the name of idle machine(s)
.SH SYNOPSIS
\fBidler [ OPTIONS ] HOSTNAME [ HOSTNAME ... ]
.SH DESCRIPTION
.I idler
uses rstat RPC calls to determine the current, 5 minute average and 15 minute
average load of machines specified on the command line. It then displays the
name and optionally the load average of the least (or most) loaded machines. 
(If there are several machines which each have the same lowest load
average, \fIidler\fR will randomly choose among them.)
.PP
.SH OPTIONS
.IP \fB\-n\fINUMBER\fR
Display the \fInumber\fR machines with the lowest load average.  By
default, \fIidler\fR displays only a single machine's name.
.IP \fB\-t\fISECONDS\fR
Sets the timeout for remote procedure calls to \fIseconds\fR seconds.
The default value is 10 seconds.
.IP \fB\-s\fIN\fR
Use the \fIN\fRth load average value for sorting, where \fIn\fR may
be either 1,2 or 3, representing the current, five minute or fifteen
minute averages. By default, \fIidler\fR uses the current load average.
.IP \fB\-l\fR
Display the actual load averages.  By default, \fIidler\fR displays only
the name(s) of the selected machine(s).
.IP \fB\-r\fR
Reverse the sense of the sort, so that \fIidler\fR shows the most loaded
machines instead of the least loaded machines.
.SH EXAMPLE
To check the most idle machine in a group of workstations:
.BR
.sp .8
   \fCidler host1 host2 host3\fR
